import { Link } from '@mui/material';
import Head from 'next/head';
import * as React from 'react';
import MenuButton from '../components/menu-button';
import { Container, StickToEndOfContainer } from '../components/styledcomponents';

function Home() {
  return (
    <Container>
      <Head>
        <title>Shaun &#38; Charlotte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MenuButton />
        <h1>Shaun &#38; Charlotte</h1>
      </main>
      <StickToEndOfContainer>
        <footer style={{marginTop: 'auto'}}>
          <span>
            Created by <Link href="https://github.com/remy90">Shaun</Link>
          </span>
        </footer>
      </StickToEndOfContainer>
    </Container>
  );
}

export default Home;