export const ACTIONS = {
  UPDATE_GUEST: 'UPDATE_GUEST',
  SUBMIT_GUEST_RSVP: 'SUBMIT_GUEST_RSVP',
  SUBMIT_PLUS_ONE_RSVP: 'SUBMIT_PLUS_ONE_RSVP',
  SUBMIT_RSVP_FORM: 'SUBMIT_RSVP_FORM',
  REMOVE_PLUS_ONE: 'REMOVE_PLUS_ONE',
};
